name: Build Android APK

# Executar manualmente
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install project dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android || true

    - name: Add SMS plugin
      run: cordova plugin add cordova-plugin-sms-receiver-sender || true

    - name: Build APK
      run: cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: smsApp-release-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk

